[project]
name = "d0058e-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.1.1",
    "crewai>=1.15.23",
    "crewai-tools>=1.15.23",
    "dataclasses>=0.8",
    "ollama>=0.6.3",
    "python-dotenv>=1.2.4",
]
